### ISSUE TITLE
Lecture 1 / slide 14: Fixed learning rate vs alpha_n

### ISSUE THREAD

**Issue by Karryanna** [ufal/npfl122#6]
The slide is titled "Fixed learning rate" but alpha_n is used in convergence condition. I suppose we could keep decreasing the learning rate and still call it fixed but maybe this could be better explained in slides?

**Comment by foxik** [comment]
The convergence condition is there to show what would be needed for correctness; however, the learning is usually fixed (or there is some decreasing schedule, but never enough to fulfill the convergence conditions [as far as what I have seen]). And when the problem is non-stationary, we do not want to converge anyway. But I am open to suggestions how to improve the slides :-)
